# Generated by Django 4.2 on 2024-10-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_likes_remove_post_views_post_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Post',
            new_name='post',
        ),
    ]
